# Generated by Django 5.2.6 on 2025-10-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current',
            field=models.CharField(choices=[('white', 'white'), ('black', 'black')], default='white', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('active', 'сейчас играют'), ('finished', 'законченная'), ('waiting', 'ожидается')], default='waiting', max_length=16),
        ),
    ]
