# Generated by Django 5.2.6 on 2026-01-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='code',
            field=models.CharField(default='123456', max_length=6),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_verifed',
            field=models.BooleanField(default=False),
        ),
    ]
